apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: hodor-acd
  creationTimestamp: null
  name: hodor
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hodor
  targetCPUUtilizationPercentage: 75
status:
  currentReplicas: 0
  desiredReplicas: 0
