apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Project
  source:
    repoURL: https://github.com/pragadees196/fampay-hodor.git
    targetRevision: othernamespace
    path: /k8s
  destinations:
  - namespace: sample
    server: https://kubernetes.default.svc
